name: sync up to codecommit

on:
  push:
    tags-ignore:
      - '*'
    branches:
      - '*'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: aws-codecommit-sync
        # You may pin to the exact commit or the version.
        # uses: afinkorea/aws-codecommit-sync@bdc7acc2538be1e2f2c926f83c25a7b3e8f216b1
        uses: afinkorea/aws-codecommit-sync@v1.0.0
        with:
          # CodeCommit repository name.
          repository_name: conversao-temperatura
          # Region of the CodeCommit repository.
          aws_region: us-east-1
          # branch
          branch: main
